namespace ExcelDynamicCase.Domain
{
    public enum CaseQuestionEnum
    {
        EulerMultiplesThreeFive = 1,
        EulerEvenFibonacci = 2,
        EulerPrimeFactorisation = 3,
        EulerLargestPalindromeProduct = 4,
        EulerEvenlyDivisibleByManyNumbers = 5,
        EulerSumOfSquaresVsSquareOfSum = 6,
        Euler10001stPrime = 7,
        EulerDigitProduct = 8,
        EulerSpecialPythagoreanTriplet = 9,
        EulerLargestProductInAGrid = 11,
        EulerHighlyDivisibleTriangleNumber = 12,
        EulerLargeSum = 13,
        EulerLatticePaths = 15,
        EulerPowerDigitSum = 16,
        EulerNumberLetterCounts = 17,
        EulerLexicographicPermutations = 24,
        EulerDigitFifthPowers = 30,
        EulerCoinSums = 31,
        EulerDigitCancellingFractions = 33,
        EulerDigitFactorials = 34,
        EulerDoubleBasePalindromes = 36,
        EulerChampernownesConstant = 40,
        EulerSubStringDivisibility = 43,
        EulerCountingSummations = 76,
        DPMMSNumbersSetsEx1Q15 = 10015,
        CodeGolf9x9Queens = 20000,
        CodeGolfReverseNATOPhoneticSpelling = 20001,
        CodeGolfAlbuquerque = 20002,
        DailyProgrammerIntegerComplexity = 30354,
        DailyProgrammerHexConversion = 30369,
        DailyProgrammerHavelHakimi = 30378,
        DailyProgrammerEasyProgressiveTaxation = 30379,
        DailyProgrammerSmooshedMorseCode1 = 30380,
        DailyProgrammerNumberOfOnes = 30390,
        DailyProgrammerMatrixSum = 30398,
        DailyProgrammerLetterValueSum = 30399,
    }
}
