using System.Collections.Generic;

namespace ExcelDynamicCase.Domain.CaseQuestions
{
    public static class CaseQuestionRepo
    {
        public static Dictionary<CaseQuestionEnum, CaseQuestion> CaseQuestions = new Dictionary<CaseQuestionEnum, CaseQuestion>()
        {
            {
                CaseQuestionEnum.EulerMultiplesThreeFive,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerMultiplesThreeFive,
                    QuestionText = "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\r\n\r\nFind the sum of all the multiples of 3 or 5 below 1000.",
                    QuestionLink = "https://projecteuler.net/problem=1",
                    Data = null,
                    Answer = "233168",
                    ExampleAnswer = 10000d,
                    Minutes = 5,
                }
            },
            {
                CaseQuestionEnum.EulerEvenFibonacci,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerEvenFibonacci,
                    QuestionText = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\r\n\r\n1,2, 3, 5, 8, 13, 21, 34, 55, 89...\r\n\r\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
                    QuestionLink = "https://projecteuler.net/problem=2",
                    Data = null,
                    Answer = "4613732",
                    ExampleAnswer = 231231d,
                    Minutes = 5,
                }
            },
            {
                CaseQuestionEnum.EulerPrimeFactorisation,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerPrimeFactorisation,
                    QuestionText = "The prime factors of 13195 are 5, 7, 13 and 29.\r\nWhat is the largest prime factor of the number 600851475143?",
                    QuestionLink = "https://projecteuler.net/problem=3",
                    Data = null,
                    Answer = "6857",
                    ExampleAnswer = 17d,
                    Minutes = 3,
                }
            },
            {
                CaseQuestionEnum.EulerLargestPalindromeProduct,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerLargestPalindromeProduct,
                    QuestionText = "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 x 99.\r\n\r\nFind the largest palindrome made from the product of two 3-digit numbers.",
                    QuestionLink = "https://projecteuler.net/problem=4",
                    Data = null,
                    Answer = "906609",
                    ExampleAnswer = 999999d,
                    Minutes = 3,
                }
            },
            {
                CaseQuestionEnum.EulerEvenlyDivisibleByManyNumbers,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerEvenlyDivisibleByManyNumbers,
                    QuestionText = "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.\r\n\r\nWhat is the smallest positive number that is dividible by all numbers from 1 to 20 with no remainder?",
                    QuestionLink = "https://projecteuler.net/problem=5",
                    Data = null,
                    Answer = "232792560",
                    ExampleAnswer = 321312d,
                    Minutes = 3,
                }
            },
            {
                CaseQuestionEnum.EulerSumOfSquaresVsSquareOfSum,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerSumOfSquaresVsSquareOfSum,
                    QuestionText = "The sum of the squares of the first 10 natural numbers is 1^2 + 2^2 + ... + 10^2 = 385\r\n\r\nThe square of the sum of the first 10 natural numbers is (1 + 2 + ... + 10)^2 = 55^2 = 3025.\r\nHence the difference is 3025 - 385 = 2640.\r\n\r\nFind the difference between the sum of the squares of the first 100 natural numbers and the square of the sum.",
                    QuestionLink = "https://projecteuler.net/problem=6",
                    Data = null,
                    Answer = "25164150",
                    ExampleAnswer = 3213129d,
                    Minutes = 3,
                }
            },
            {
                CaseQuestionEnum.Euler10001stPrime,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.Euler10001stPrime,
                    QuestionText = "By listing the first 6 prime numbers 2, 3, 5, 7, 11 and 13 we can see that the 6th prime is 13.\r\n\r\nWhat is the 10,001st prime number?",
                    QuestionLink = "https://projecteuler.net/problem=7",
                    Data = null,
                    Answer = "104743",
                    ExampleAnswer = 31237911d,
                    Minutes = 10,
                }
            },
            {
                CaseQuestionEnum.EulerDigitProduct,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerDigitProduct,
                    QuestionText = "The 4 adjacent digits in this 1000-digit number that have the greatest product are 9x9x8x9 = 5832.\r\nFind the 13 adjacent digits that have the greatest product, what is their product?\r\n\r\n7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450",
                    QuestionLink = "https://projecteuler.net/problem=8",
                    Data = null,
                    Answer = "23514624000",
                    ExampleAnswer = 2310310d,
                    Minutes = 5,
                }
            },
            {
                CaseQuestionEnum.EulerSpecialPythagoreanTriplet,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerSpecialPythagoreanTriplet,
                    QuestionText = "A Pythagorean triplet is a set of 3 natural numbers a < b < c for which a^2 + b^2 = c^2.\r\n\r\nFor example, 3^2+4^2=9+16=25=5^2.\r\n\r\nThere exists exactly one Pythagorean triplet for which a+b+c=1000.\r\nFind the product abc.",
                    QuestionLink = "https://projecteuler.net/problem=9",
                    Data = null,
                    Answer = "31875000",
                    ExampleAnswer = 3217390127d,
                    Minutes = 5,
                }
            },
            {
                CaseQuestionEnum.EulerLargestProductInAGrid,
                new CaseQuestion()
                {
                    Id = CaseQuestionEnum.EulerLargestProductInAGrid,
                    QuestionText = "What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20x20 grid?",
                    QuestionLink = "https://projecteuler.net/problem=11",
                    Data = new Dictionary<string, object[,]>()
                    {
                        {
                            "Grid",
                            new object[,]
                            {
                                {8d, 2d, 22d, 97d, 38d, 15d, 0d, 40d, 0d, 75d, 4d, 5d, 7d, 78d, 52d, 12d, 50d, 77d, 91d, 8d},
                                {49d, 49d, 99d, 40d, 17d, 81d, 18d, 57d, 60d, 87d, 17d, 40d, 98d, 43d, 69d, 48d, 4d, 56d, 62d, 0d},
                                {81d, 49d, 31d, 73d, 55d, 79d, 14d, 29d, 93d, 71d, 40d, 67d, 53d, 88d, 30d, 3d, 49d, 13d, 36d, 65d},
                                {52d, 70d, 95d, 23d, 4d, 60d, 11d, 42d, 69d, 24d, 68d, 56d, 1d, 32d, 56d, 71d, 37d, 2d, 36d, 91d},
                                {22d, 31d, 16d, 71d, 51d, 67d, 63d, 89d, 41d, 92d, 36d, 54d, 22d, 40d, 40d, 28d, 66d, 33d, 13d, 80d},
                                {24d, 47d, 32d, 60d, 99d, 3d, 45d, 2d, 44d, 75d, 33d, 53d, 78d, 36d, 84d, 20d, 35d, 17d, 12d, 50d},
                                {32d, 98d, 81d, 28d, 64d, 23d, 67d, 10d, 26d, 38d, 40d, 67d, 59d, 54d, 70d, 66d, 18d, 38d, 64d, 70d},
                                {67d, 26d, 20d, 68d, 2d, 62d, 12d, 20d, 95d, 63d, 94d, 39d, 63d, 8d, 40d, 91d, 66d, 49d, 94d, 21d},
                                {24d, 55d, 58d, 5d, 66d, 73d, 99d, 26d, 97d, 17d, 78d, 78d, 96d, 83d, 14d, 88d, 34d, 89d, 63d, 72d},
                                {21d, 36d, 23d, 9d, 75d, 0d, 76d, 44d, 20d, 45d, 35d, 14d, 0d, 61d, 33d, 97d, 34d, 31d, 33d, 95d},
                                {78d, 17d, 53d, 28d, 22d, 75d, 31d, 67d, 15d, 94d, 3d, 80d, 4d, 62d, 16d, 14d, 9d, 53d, 56d, 92d},
                                {16d, 39d, 5d, 42d, 96d, 35d, 31d, 47d, 55d, 58d, 88d, 24d, 0d, 17d, 54d, 24d, 36d, 29d, 85d, 57d},
                                {86d, 56d, 0d, 48d, 35d, 71d, 89d, 7d, 5d, 44d, 44d, 37d, 44d, 60d, 21d, 58d, 51d, 54d, 17d, 58d},
                                {19d, 80d, 81d, 68d, 5d, 94d, 47d, 69d, 28d, 73d, 92d, 13d, 86d, 52d, 17d, 77d, 4d, 89d, 55d, 40d},
                                {4d, 52d, 8d, 83d, 97d, 35d, 99d, 16d, 7d, 97d, 57d, 32d, 16d, 26d, 26d, 79d, 33d, 27d, 98d, 66d},
                                {88d, 36d, 68d, 87d, 57d, 62d, 20d, 72d, 3d, 46d, 33d, 67d, 46d, 55d, 12d, 32d, 63d, 93d, 53d, 69d},
                                {4d, 42d, 16d, 73d, 38d, 25d, 39d, 11d, 24d, 94d, 72d, 18d, 8d, 46d, 29d, 32d, 40d, 62d, 76d, 36d},
                                {20d, 69d, 36d, 41d, 72d, 30d, 23d, 88d, 34d, 62d, 99d, 69d, 82d, 67d, 59d, 85d, 74d, 4d, 36d, 16d},
                                {20d, 73d, 35d, 29d, 78d, 31d, 90d, 1d, 74d, 31d, 49d, 71d, 48d, 86d, 81d, 16d, 23d, 57d, 5d, 54d},
                                {1d, 70d, 54d, 71d, 83d, 51d, 54d, 69d, 16d, 92d, 33d, 48d, 61d, 43d, 52d, 1d, 89d, 19d, 67d, 48d},
                            }
                        }
                    },
                    Answer = "70600674",
                    ExampleAnswer = 3219037d,
                    Minutes = 5f,
                }
            }
        };
    }
}
